### ISSUE TITLE
UndefVarError in current version

### ISSUE THREAD

**Issue by paulobruno** [natema/WorldDynamics.jl#19]
Instantiating the current version and running it gives us the following error:
```
ERROR: LoadError: UndefVarError: [VARIABLE] not defined
```

**Comment by paulobruno** [comment]
The code runs fine with the `Project.toml` from bb20a33. Although the code will still break in newer versions of ModelingToolkit, it does not break anymore using `instantiate`. Therefore, I changing this from `bug` to `enhancement`.

**Comment by universmile** [comment]
In Issue #60, we fixed some issues of fluctuations by using a different solver from ModelingToolkit. However, we observed that those issues are also related to the Julia version being used. 

More precisely, for the same versions of the packages DifferentialEquations (`v7.3.0`) and ModelingToolkit (v8.16.0) :
- Under `Julia v1.8.1,` the fluctuations disappeared.
- Under `Julia v1.7.2`, the plots exhibited fluctuations. 

Perhaps newer versions of ModelingToolkit are even better to deal with some cases, but the maximum version that we currently accept is 8.16 because of the error that we get in most recent versions (see above comment by @paulobruno ).

We might want to consider at some point restricting to Julia versions greater than 1.8.

**Comment by paulobruno** [comment]
As defined in #103, all code that is breaking, even in a specific scenario, should be labeled as `bug`.

**Comment by natema** [comment]
> Should we bump the ModelingToolkit version?

Yes!

**Comment by paulobruno** [comment]
Good, then i'll proceed with the tests using the new version.

**Comment by paulobruno** [comment]
Fixed by #112
